### ISSUE TITLE
update the announcements section in homepage

### ISSUE THREAD

**Issue by pratikpakhale** [Velocity-IIITDWD/iiitdwd.ac.in#105]
figma - https://www.figma.com/design/riu3hpDJlEM91jcDJkpLuo/IIIT-Dharwad---Main-Page?node-id=1-2&t=BVPwNWfLm0Oxp0HH-0

![image](https://github.com/Velocity-IIITDWD/iiitdwd.ac.in/assets/48487283/994cc516-ce0e-4b5c-9b46-f3e6dc50f6b8)

The announcements would be auto scrolling.

**Comment by C-NikhilKarthik** [comment]
Working on it
