### ISSUE TITLE
Old search engine crawled page not redirecting to new webpages

### ISSUE THREAD

**Issue by harshsoni-harsh** [Velocity-IIITDWD/iiitdwd.ac.in#208]
![S.E. crawled pages](https://github.com/Velocity-IIITDWD/iiitdwd.ac.in/assets/52278293/c47595dd-e770-4850-b14f-505e82b5db1c)
Similar pages are currently not redirected to the new webpages, but can be done by having .htaccess rules like this "Redirect 301 /pagename.php http://www.domain.com/pagename.html" - https://linchpinseo.com/blog/htaccess-rules/ 

Add them for the pages listed here - https://octopus.do/sxigzvd9fs (atleast the major pages)

**Comment by pratikpakhale** [comment]
Instead of relying on Apache server just [redirect using nextjs](https://nextjs.org/docs/app/building-your-application/routing/redirecting).

Manually mapping the necessary routes.
