### ISSUE TITLE
Hamburger menu's content's font size is too small

### ISSUE THREAD

**Issue by Vedabahu** [Velocity-IIITDWD/iiitdwd.ac.in#243]
The contents of the hamburger menu's font is too small on mobiles causing miss clicks. Please increase the font size.

![image](https://github.com/Velocity-IIITDWD/iiitdwd.ac.in/assets/79869936/aef7702a-d1db-4c60-855b-ed071729cdfa)

The left side part.

**Comment by pratikpakhale** [comment]
@AyushSingh916 can you take a look at this.

**Comment by AyushSingh916** [comment]
I have raised a pr.

**Comment by pratikpakhale** [comment]
It's better to link issues in PR to auto close thhem. I have merged the PR. 

Thank you! :saluting_face:
