### ISSUE TITLE
add page - /academics home 

### ISSUE THREAD

**Issue by pratikpakhale** [Velocity-IIITDWD/iiitdwd.ac.in#47]
- add curriculum button in the homepage which links to the entire curriculum 
- add a redirect link text at the end of each course table in each branch (cse, dsai, ece) naming 'Curriculum' which links to curriculum pdf

**Comment by pratikpakhale** [comment]
also add KRC link,
#57

**Comment by C-NikhilKarthik** [comment]
issue has been completed
