### ISSUE TITLE
add pages - BOG, Senate, Research, Staff, Building and Works, etc

### ISSUE THREAD

**Issue by pratikpakhale** [Velocity-IIITDWD/iiitdwd.ac.in#55]
All of the following pages have the same format, 

https://iiitdwd.ac.in/former_director.php
https://iiitdwd.ac.in/visitor.php
https://iiitdwd.ac.in/Bog.php
https://iiitdwd.ac.in/Bog2.php
https://iiitdwd.ac.in/senate.php
https://iiitdwd.ac.in/Finance_committee.php
https://iiitdwd.ac.in/staff.php
https://iiitdwd.ac.in/Expert_committee.php
https://iiitdwd.ac.in/Research.php

so one generic component which handles 
- title
- section
    - section title
    - profiles 
        - profile image
        - profile name
        - profile description
  
Some pages may or may not have sections, there direct profiles are shown. 

Person working on this is expected to,
- create a generic component for all the pages
- create pages for all and then use the component there

**Comment by boxlesscat** [comment]
gonna do this
